import numpy as np
print("Joining NumPy Arrays")

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.concatenate((a, b))
print(result)
st = np.stack((a, b), axis=1)
print(st)

arr = np.hstack((a, b))
print(a, b)
arrr = np.dstack((a, b))
print(arrr)

print("Splitting NumPy Arrays")

arr2 = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr2, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])
sp = np.array_split(arr, 3)
print(sp)
arr3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
sp = np.array_split(arr3, 3, axis=1)
print(sp)
hs = np.hsplit(arr3, 3)
print(hs)

print("Searching Arrays")
arr3 = np.array([1, 2, 3, 4, 4, 3, 6, 2, 7, 8])
x = np.where(arr3 % 2 == 0)
print(x)
x = np.searchsorted(arr3, 7)
print(x)
print("Sorting Arrays")
arr4 = np.array([True, False, True])
print(np.sort(arr4))
arr5 = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr5))
